language: python
python:
- 3.6.3
branches:
  only:
  - dev
#before_install:
#- chmod 600 ~/.ssh/id_rsa
#- eval $(ssh-agent)
#- ssh-add ~/.ssh/id_rsa
#- cp .travis/ssh_config ~/.ssh/config
#- echo -e "Host 127.0.0.1:8000\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
- sudo easy_install pip
- pip install --upgrade itsdangerous
- pip install --upgrade Werkzeug
- pip install --upgrade Jinja2
- pip install --upgrade flask
- pip install gunicorn
script: 
- gunicorn -b 127.0.0.1:5000 hello:app
